### PR TITLE
Added xp for FurnaceRecipe

### PR DESCRIPTION
**Pull request by hibo98**
This is required for [GlowstonePlusPlus#189](https://github.com/GlowstonePlusPlus/GlowstonePlusPlus/pull/189)

### CODE REVIEW

**Comment by Paulomart** [comment]
PR this here to?: https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/browse/src/main/java/org/bukkit/inventory/FurnaceRecipe.java

**Comment by hibo98** [comment]
Okay, I'll do this in few minutes

**Comment by Paulomart** [comment]
Was just a idea, you dont have to :)

**Comment by mastercoms** [comment]
Could data be added, along with getters and setters? I know it is ignored, but it would still be good to store it if we needed it.

**Comment by hibo98** [comment]
Which _data_ MaterialData, for result or source?
And I don't imagine of case in that we need that.

**Comment by hibo98** [comment]
I think this can be pulled, because in Bukkit 1.9 it is allready pulled.
https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/pull-requests/116/overview

**Pull request merged**
