### PR TITLE
Simplification

### PR DESCRIPTION
**Pull request by BalloonChamp**
These command simplifications should, in my opinion as a server owner, make our live easier!

### CODE REVIEW

**Comment by BalloonChamp** [comment]
Not my fault that the Circleci check failed... it was the "No such file or directory for the output directory"...

**Comment by mastercoms** [comment]
I don't think we should deviate from the vanilla command format.

**Comment by BalloonChamp** [comment]
OK, just a thought. Sorry for wasting your time.

**Comment by mastercoms** [comment]
It was not a waste of my time, don't feel bad about it.

**Comment by deathcap** [comment]
@BalloonChamp you can add these aliases in your local configuration in `config/commands.yml` FYI

**Pull request closed without merging**
