### PR TITLE
[WIP] Add player sounds

### PR DESCRIPTION
**Pull request by twizmwazin**
I'll be using these too

### CODE REVIEW

**Comment by mastercoms** [comment]
What about neutral.hurt, neutral.hurt.fall.big, neutral.hurt.fall.small, neutral.swim, neutral.swim.splash, hostile.hurt.fall.big, hostile.hurt.fall.small, hostile.swim, and hostile.swim.splash?

**Comment by twizmwazin** [comment]
Sorry about that, I'll get those tomorrow and also update the gpp pr

**Comment by mastercoms** [comment]
Ok, thank you!

**Comment by mastercoms** [comment]
I'll just merge these for now and you can make a new pull request for the missing sounds.

**Comment by twizmwazin** [comment]
Oh sorry about being inactive with this, collage deadline tonight. Should have free time tomorrow

**Comment by mastercoms** [comment]
i feel you :) it's totally fine!

**Pull request merged**
